### ISSUE TITLE
Error Exchange Setup Mismatch

### ISSUE THREAD

**Issue by ritasker** [pardahlman/RawRabbit#202] opened 2017-03-14 11:21 UTC
When using pub/sub if an exception in thrown in the consumer (subscriber) an error exchange is declared. The Durability is set to false, the default value of the `bool` used in the `ExchangeConfiguration` (https://github.com/pardahlman/RawRabbit/blob/stable/src/RawRabbit/Configuration/Exchange/ExchangeConfiguration.cs#L9).

When subscribing to the `HandlerExceptionMessage` the subscriber tries to bind to the exchange and fails due to the default value used in the `WithDurability` extension being `true` (https://github.com/pardahlman/RawRabbit/blob/master/src/RawRabbit/Configuration/Exchange/IExchangeConfigurationBuilder.cs#L7).

**Comment by pardahlman** [comment] 2017-03-15 11:28
Thanks for reporting this! I haven't had time to look into this issue in detail, though I'm not sure that  the source of the problem is the `ExchangeConfigurationBuilder`. The default argument for `.WithDurable()` is there so that you can call the method without any argument. The method still needs to be invoked to set durability.

You are right, though, there is an issue here. It looks like the default error handler [uses `ExchangeConfiguration.Default`](https://github.com/pardahlman/RawRabbit/blob/stable/src/RawRabbit/ErrorHandling/DefaultStrategy.cs#L34), which will declare the exchange [without honoring the `GeneralExchangeConfiguration` value](https://github.com/pardahlman/RawRabbit/blob/stable/src/RawRabbit/Configuration/Exchange/ExchangeConfiguration.cs#L21).

A work-around could be what we're doing [in the error handling tests](https://github.com/pardahlman/RawRabbit/blob/master/test/RawRabbit.IntegrationTests/Features/MessageHandlerExceptionTests.cs#L144-L154) and explicitly specify the exchange as none-durability 

```csharp
client.SubscribeAsync<HandlerExceptionMessage>(async (message, context) =>
{
    // handler here...
}, c => c
    .WithExchange(e => e
        .WithName(conventions.ErrorExchangeNamingConvention())
        .WithDurability(false))
    .WithQueue(q => q
        .WithArgument(QueueArgument.MessageTtl, (int)TimeSpan.FromSeconds(1).TotalMilliseconds)
        .WithAutoDelete())
    .WithRoutingKey("#")
);
```
I would say that the root of the problem is that the error handler doesn't honor the `GeneralExchangeConfiguraiton`. The error handling is rewritten in 2.0 and there is no active development for 1.x. However, we _might_ release 1.10.4 of the client, and if so a PR for this ticket would be reviewed and accepted.

**Comment by pardahlman** [comment] 2017-12-09 13:18
Closing this, as this is correctly implemented in the most current version

**Closed by pardahlman** 2017-12-09 13:18 UTC
Labels: bug
