### ISSUE TITLE
Error in BusClientFactory.CreateDefault() on net core 2.0

### ISSUE THREAD

**Issue by Kilovatiy** [pardahlman/RawRabbit#257] opened 2017-08-17 11:53 UTC
Hi, 
I use RawRabbit.vNext version 1.10.3.
I update my app from core 1.2 to core 2.0 and start receiving an error - 
Method not found:` 'System.IServiceProvider Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(Microsoft.Extensions.DependencyInjection.IServiceCollection)'. `

Here is stack trace:
`  at RawRabbit.vNext.BusClientFactory.CreateDefault(IServiceCollection services)
   at IBE.Amadeus.SessionPool.MessageQueueClientFactory.GetSingletonInstance(RawRabbitConfiguration config) in C:\Work_proj\ibe-backend\IBE.Amadeus.SessionPool\MessageQueueClientFactory.cs:line 27
   at IBE.Amadeus.SessionPool.ServiceCollectionExtensions.<>c__DisplayClass0_0.<AddSessionPool>b__0(IServiceProvider ioc) in C:\Work_proj\ibe-backend\IBE.Amadeus.SessionPool\ServiceCollectionExtensions.cs:line 34
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass22_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.Internal.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()`

Thanks

**Comment by pardahlman** [comment] 2017-08-19 07:50
Hi, @Kilovatiy - thanks for reporting this. I haven't had time to look into the changes of .NET Core 2.0, but apparently some contracts have changed. I'm focusing on v 2.0 of RawRabbit ATM, but feel free to submit a PR for this!

**Comment by pardahlman** [comment] 2017-08-20 07:46
Not sure what the underlying problem is. Based on this https://github.com/aspnet/EntityFrameworkCore/issues/8498#issuecomment-315570837 it sounds like the problem can be resolved by removing the bin folder.

I looked into the possibility to upgrade `Microsoft.Extensions.DependencyInjection` to version 2.0.0, but it requires .NET Standard 2.0 which is a higher version than currently supported.

**Comment by samirski** [comment] 2017-08-23 15:11
I think this has something to do with the netcoreapp assembly bindings. Strangely enough this exception is not being thrown in a .net core console application but only in a .net core web application for whatever reason. So I took a look in the BusClientFactory class and tried to construct the objects the same way in my code. Long story short everything works now as expected. It might be a bit cumbersome but frankly speaking I don't care as the bus client object can be stored in a IoC container as well. So my code looks like this now:
`
 var services = new ServiceCollection().AddRawRabbit(
                cfg => cfg.SetBasePath(Directory.GetCurrentDirectory()).AddJsonFile("rawrabbit.json"),
                ioc => ioc.AddSingleton<RawRabbit.Logging.ILoggerFactory, RawRabbit.Logging.Serilog.LoggerFactory>());

            var serviceProvider = services.BuildServiceProvider();
            var client = serviceProvider.GetService<IBusClient>();
            var busClient = new RawRabbit.vNext.Disposable.BusClient(client);
`

and similarly while using the AdvancedMessageContext:
`
var services = new ServiceCollection().AddRawRabbit<AdvancedMessageContext>(
                cfg => cfg.SetBasePath(Directory.GetCurrentDirectory()).AddJsonFile("rawrabbit.json"),
                ioc => ioc.AddSingleton<RawRabbit.Logging.ILoggerFactory, RawRabbit.Logging.Serilog.LoggerFactory>());

            var serviceProvider = services.BuildServiceProvider();
            var client = serviceProvider.GetService<IBusClient<AdvancedMessageContext>>();
            var busClient = new RawRabbit.vNext.Disposable.BusClient<AdvancedMessageContext>(client);
`

**Comment by MrGlenThomas** [comment] 2017-08-24 10:18
I have the same problem. RawRabbit in .NET Core 2.0 console application was fine, .NET Core 2.0 web hosted application is not working, with above error.

@samirski I don't understand your solution. You are adding RawRabbit to DI service provider, but then you are instantiating the bus client without using the service provider..? Why not just skip adding it to the service collection?

**Comment by MrGlenThomas** [comment] 2017-08-24 13:59
It looks like an upgrade to .NET Standard 2.0 is the only option. @pardahlman If I submitted a PR for an upgrade to 2.0 would you be ok with that or looking to keep compatibility with lower version?

Will RawRabbit v2 target .NET Standard 2.0?

**Comment by MrGlenThomas** [comment] 2017-08-24 14:30
Can work around this by resolving RawRabbit.IBusClient instead of RawRabbit.vNext.Disposable.IBusClient

**Comment by pardahlman** [comment] 2017-08-24 15:18
@MrGlenThomas I'm hesitant to target .NET Standard 2.0, as it will break compatibility with users that target a framework compatible with a lower standard (for example .NET Framework 4.6). The idea with .NET Standard is that a higher version is a super-set of all previous versions. This also makes sense [according to this article on .NET Standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard)

> When choosing a .NET Standard version, you should consider this trade-off:
>
>  * The higher the version, the more APIs are available to you.
>  * The lower the version, the more platforms implement it.
>
>In general, we recommend you to target the lowest version of .NET Standard possible.

**Comment by pardahlman** [comment] 2017-08-24 15:24
My gut feeling is that something has changed in `Microsoft.Extensions.DependencyInjection`. However, I will be more than happy to accept a PR that fixes this issue without changing target framework.

**Comment by MrGlenThomas** [comment] 2017-08-24 15:30
It does appear that a change to the DI is the cause and the only way around it (without .NET Standard 2.0) would be to add a new method of building the BusClient object graph that doesn't use the .NET DI library. Maybe could allow people to use alternative containers like structuremap/autofac/ etc.

**Comment by jwoodman510** [comment] 2017-09-06 18:04
Facing the same issue here as I have just upgraded the majority of my projects to 2.0

Would it be possible to release a separate version, or even a separate package, that specifically targets .NET Standard 2.0?

**Comment by pardahlman** [comment] 2017-09-10 10:54
So [this comment](https://github.com/aspnet/EntityFrameworkCore/issues/8498#issuecomment-326887331) sums it up

> You need to update to ASP.NET Core 2.0. Anything that called BuildServiceProvider needs to be updated.

Unfortunately, `Microsoft.Extensions.*` packages depends on `netstandard2.0`, and by upgrading the RawRabbit vNext package, the extensions package needs to be upgraded as well. The lowest level of .NETFramework that supports `netstandard2.0` is 4.6.1 (RawRabbit suppoort 4.5.1 atm).

Not sure how to resolve this issue. The work-around (above) seems like a acceptable workaround for now.

**Comment by Manny651** [comment] 2017-09-11 13:22
How about having multiple target frameworks in the csproj?

**Comment by pardahlman** [comment] 2017-09-23 12:25
Hi @Manny651 - thanks for the input. RawRabbit already has [multiple targets](https://github.com/pardahlman/RawRabbit/blob/stable/src/RawRabbit/RawRabbit.csproj#L8), which is part of the problem. Can you elaborate on what you mean?

**Closed** 2017-09-29 16:52 UTC

**Comment by srinathgnath** [comment] 2018-04-25 16:55
@jwoodman510  How to set Rawrabbit configuration with this approach?
