### ISSUE TITLE
RawRabbit 2.0.0-rc1 & Autofac 4.2.0 - Channels not closing

### ISSUE THREAD

**Issue by afmuller** [pardahlman/RawRabbit#288] opened 2017-10-31 09:15 UTC
Hi. 

When using AutoFac it appears channels are not being closed on application shutdown (after publishing). 

When using the below Startup.cs in my ASP.NET Core 2 application (which does NOT use AutoFac), I get the below logs at application shutdown time (everything seems to work correctly).

**Startup.cs file:**
`
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            
            services.AddRawRabbit(new RawRabbitOptions
            {
                ClientConfiguration = new RawRabbit.Configuration.RawRabbitConfiguration()
                {
                    Username = Configuration["RabbitMqConfig:Username"],
                    Password = Configuration["RabbitMqConfig:Password"],
                    Port = int.Parse(Configuration["RabbitMqConfig:Port"]),
                    VirtualHost = Configuration["RabbitMqConfig:VirtualHost"],
                    Hostnames = { Configuration["RabbitMqConfig:Hostname"], },
                },
            });
            

            services.AddMvc();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseMvc();
        }
    }

` 
**Logs**
![withoutautofac](https://user-images.githubusercontent.com/15875383/32215686-59d897cc-be2b-11e7-8e11-8ab97392279a.PNG)

`
PS D:\Data\Code\VStest\RawRabbit\RawRabbitTest\WebApi> dotnet run
Using launch settings from D:\Data\Code\VStest\RawRabbit\RawRabbitTest\WebApi\Properties\launchSettings.json...
2017-10-31 11:00:50 [Information] User profile is available. Using '"C:\\Users\\andrewm.EKH\\AppData\\Local\\ASP.NET\\DataProtection-Keys"' as key repository and Windows DPAPI to encrypt keys at rest.
Hosting environment: Development
Content root path: D:\Data\Code\VStest\RawRabbit\RawRabbitTest\WebApi
Now listening on: http://localhost:53524
Application started. Press Ctrl+C to shut down.
2017-10-31 11:00:55 [Information] Request starting HTTP/1.1 POST http://localhost:53524/api/values application/json 32
2017-10-31 11:00:55 [Information] Executing action method "WebApi.Controllers.ValuesController.Post (WebApi)" with arguments (["Core.User"]) - ModelState is Valid
2017-10-31 11:00:55 [Debug] Creating a new connection for 1 hosts.
2017-10-31 11:00:55 [Debug] Stage "Initialized" has no additional middlewares registered.
2017-10-31 11:00:55 [Debug] Stage "ProducerInitialized" has no additional middlewares registered.
2017-10-31 11:00:55 [Debug] Stage "PublishConfigured" has no additional middlewares registered.
2017-10-31 11:00:55 [Debug] Exchange configuration found. Declaring 'core'.
2017-10-31 11:00:55 [Information] Declaring exchange "core".
2017-10-31 11:00:55 [Debug] Existing connection is open and will be used.
2017-10-31 11:00:55 [Debug] Done processing topology work.
2017-10-31 11:00:55 [Debug] Stage "ExchangeDeclared" has no additional middlewares registered.
2017-10-31 11:00:55 [Debug] Stage "MessageSerialized" has no additional middlewares registered.
2017-10-31 11:00:55 [Debug] Stage "BasicPropertiesCreated" has no additional middlewares registered.
2017-10-31 11:00:55 [Debug] Pool currently has 0, which is lower than the minimal pool size 1. Creating channels.
2017-10-31 11:00:55 [Debug] Existing connection is open and will be used.
2017-10-31 11:00:55 [Debug] Starting serving channels.
2017-10-31 11:00:55 [Debug] Stage "ChannelCreated" has no additional middlewares registered.
2017-10-31 11:00:55 [Debug] No Mandatory Callback registered.
2017-10-31 11:00:55 [Information] Setting 'Publish Acknowledge' for channel '2'
2017-10-31 11:00:55 [Information] Setting up publish acknowledgement for 1 with timeout 0:00:01
2017-10-31 11:00:55 [Debug] Stage "PreMessagePublish" has no additional middlewares registered.
2017-10-31 11:00:55 [Information] Performing basic publish with routing key "user" on exchange "core".
2017-10-31 11:00:55 [Debug] Stage "MessagePublished" has no additional middlewares registered.
2017-10-31 11:00:56 [Information] Executing HttpStatusCodeResult, setting HTTP status code 200
2017-10-31 11:00:56 [Information] Executed action "WebApi.Controllers.ValuesController.Post (WebApi)" in 395.689ms
2017-10-31 11:00:56 [Information] Request finished in 505.9488ms 200
Application is shutting down...
**PS D:\Data\Code\VStest\RawRabbit\RawRabbitTest\WebApi> 2017-10-31 11:01:02 [Information] Channel 2 is being closed by the application. No recovery will be performed.**
PS D:\Data\Code\VStest\RawRabbit\RawRabbitTest\WebApi>
`

_Note the "[Information] Channel 2 is being closed by the application. No recovery will be performed." logs after application shutdown._

However, when including AutoFac in the Startup.cs (see below), the channels are not closed at application shutdown. I get a stream of the this log message AFTER I have terminated the application "[Debug] Channel pool currently has 1 channels open and a total workload of 0". It appears there is a background thread that is not terminating. 

**Startup.cs WITH AutoFac**
`
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public IServiceProvider ConfigureServices(IServiceCollection services)
        {
            
            services.AddRawRabbit(new RawRabbitOptions
            {
                ClientConfiguration = new RawRabbit.Configuration.RawRabbitConfiguration()
                {
                    Username = Configuration["RabbitMqConfig:Username"],
                    Password = Configuration["RabbitMqConfig:Password"],
                    Port = int.Parse(Configuration["RabbitMqConfig:Port"]),
                    VirtualHost = Configuration["RabbitMqConfig:VirtualHost"],
                    Hostnames = { Configuration["RabbitMqConfig:Hostname"], },
                },
            });
            

            services.AddMvc();

            // Configure Autofac service provider
            var containerBuilder = new ContainerBuilder();
            containerBuilder.Populate(services);
            var container = containerBuilder.Build();
            return container.Resolve<IServiceProvider>();

        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseMvc();
        }
    }

`
**Logs showing channel not closing:**
![withautofac](https://user-images.githubusercontent.com/15875383/32215694-5f64c986-be2b-11e7-9130-0820988caa71.PNG)

`
PS D:\Data\Code\VStest\RawRabbit\RawRabbitTest\WebApi> dotnet run
Using launch settings from D:\Data\Code\VStest\RawRabbit\RawRabbitTest\WebApi\Properties\launchSettings.json...
2017-10-31 10:54:21 [Information] User profile is available. Using '"C:\\Users\\andrewm.EKH\\AppData\\Local\\ASP.NET\\DataProtection-Keys"' as key repository and Windows DPAPI to encrypt keys at rest.
Hosting environment: Development
Content root path: D:\Data\Code\VStest\RawRabbit\RawRabbitTest\WebApi
Now listening on: http://localhost:53524
Application started. Press Ctrl+C to shut down.
2017-10-31 10:54:24 [Information] Request starting HTTP/1.1 POST http://localhost:53524/api/values application/json 32
2017-10-31 10:54:24 [Information] Executing action method "WebApi.Controllers.ValuesController.Post (WebApi)" with arguments (["Core.User"]) - ModelState is Valid
2017-10-31 10:54:24 [Debug] Creating a new connection for 1 hosts.
2017-10-31 10:54:25 [Debug] Stage "Initialized" has no additional middlewares registered.
2017-10-31 10:54:25 [Debug] Stage "ProducerInitialized" has no additional middlewares registered.
2017-10-31 10:54:25 [Debug] Stage "PublishConfigured" has no additional middlewares registered.
2017-10-31 10:54:25 [Debug] Exchange configuration found. Declaring 'core'.
2017-10-31 10:54:25 [Information] Declaring exchange "core".
2017-10-31 10:54:25 [Debug] Existing connection is open and will be used.
2017-10-31 10:54:25 [Debug] Done processing topology work.
2017-10-31 10:54:25 [Debug] Stage "ExchangeDeclared" has no additional middlewares registered.
2017-10-31 10:54:25 [Debug] Stage "MessageSerialized" has no additional middlewares registered.
2017-10-31 10:54:25 [Debug] Stage "BasicPropertiesCreated" has no additional middlewares registered.
2017-10-31 10:54:25 [Debug] Pool currently has 0, which is lower than the minimal pool size 1. Creating channels.
2017-10-31 10:54:25 [Debug] Existing connection is open and will be used.
2017-10-31 10:54:25 [Debug] Starting serving channels.
2017-10-31 10:54:25 [Debug] Stage "ChannelCreated" has no additional middlewares registered.
2017-10-31 10:54:25 [Debug] No Mandatory Callback registered.
2017-10-31 10:54:25 [Information] Setting 'Publish Acknowledge' for channel '2'
2017-10-31 10:54:25 [Information] Setting up publish acknowledgement for 1 with timeout 0:00:01
2017-10-31 10:54:25 [Debug] Stage "PreMessagePublish" has no additional middlewares registered.
2017-10-31 10:54:25 [Information] Performing basic publish with routing key "user" on exchange "core".
2017-10-31 10:54:25 [Debug] Stage "MessagePublished" has no additional middlewares registered.
2017-10-31 10:54:25 [Information] Executing HttpStatusCodeResult, setting HTTP status code 200
2017-10-31 10:54:25 [Information] Executed action "WebApi.Controllers.ValuesController.Post (WebApi)" in 384.6118ms
2017-10-31 10:54:25 [Information] Request finished in 495.2786ms 200
2017-10-31 10:54:35 [Debug] Channel pool currently has 1 channels open and a total workload of 0
**Application is shutting down...
PS D:\Data\Code\VStest\RawRabbit\RawRabbitTest\WebApi>
PS D:\Data\Code\VStest\RawRabbit\RawRabbitTest\WebApi> 2017-10-31 10:54:45 [Debug] Channel pool currently has 1 channels open and a total workload of 02017-10-31 10:54:55 [Debug] Channel pool currently has 1 channels open and a total workload of 0
2017-10-31 10:55:05 [Debug] Channel pool currently has 1 channels open and a total workload of 0
2017-10-31 10:55:15 [Debug] Channel pool currently has 1 channels open and a total workload of 0**

`

I have also tried the below configuration but it does the same:

`
        public IServiceProvider ConfigureServices(IServiceCollection services)
        {

            services.AddMvc();

            // Configure Autofac service provider
            var containerBuilder = new ContainerBuilder();
            //Setup DI dependencies from this project
            
            containerBuilder.RegisterRawRabbit(new RawRabbitOptions
            {
                ClientConfiguration = new RawRabbit.Configuration.RawRabbitConfiguration()
                {
                    Username = Configuration["RabbitMqConfig:Username"],
                    Password = Configuration["RabbitMqConfig:Password"],
                    Port = int.Parse(Configuration["RabbitMqConfig:Port"]),
                    VirtualHost = Configuration["RabbitMqConfig:VirtualHost"],
                    Hostnames = { Configuration["RabbitMqConfig:Hostname"], },
                    AutoCloseConnection = true,
                    AutomaticRecovery = true
                }
            });
            
            containerBuilder.Populate(services);
            var container = containerBuilder.Build();
            return container.Resolve<IServiceProvider>();

        }
`

**Comment by pardahlman** [comment] 2017-11-01 06:21
Hi @afmuller - thanks for reporting this. I'll try to reproduce this later this week.

**Comment by yeowgit** [comment] 2017-11-09 10:27
Hi,
I have same problem with RabbitMQ connection being open after all Models are closed. 
I think AutoCloseConnection property in RawRabbitConfiguration is not being to the AutoClose RabbitMQ connection property.

thanks

**Comment by liri2006** [comment] 2017-12-19 20:15
I have same issue with .net core 2 console application - started getting "open channel" logs after performing Publish.
RawRabbit 2.0.0-rc2
![image](https://user-images.githubusercontent.com/2411723/34176859-bff83f6a-e501-11e7-87f7-dd3928b26858.png)

**Comment by pardahlman** [comment] 2017-12-20 12:29
Thanks for reporting this. I'll have a closer look at this.

**Comment by pardahlman** [comment] 2018-01-25 20:16
I tried to reproduce this in a sample console app without involving ASP.NET Core's DI

```csharp
var container = new ContainerBuilder()
    .RegisterRawRabbit(new RawRabbitOptions
    {
        ClientConfiguration = new ConfigurationBuilder()
            .SetBasePath(Directory.GetCurrentDirectory())
            .AddJsonFile("rawrabbit.json")
            .Build()
            .Get<RawRabbitConfiguration>(),
        Plugins = p => p
            .UseGlobalExecutionId()
            .UseMessageContext<MessageContext>()
    })
    .Build();
```

So basically create container builder, register RawRabbit and build the container. I'm not able to reproduce this with that setup. I'm not 100% how lifetime scope management it handled when using `Autofac.Extensions.DependencyInjection`. Are you able to provide a small, console application that demonstrates this behavior? Thanks!

**Comment by pardahlman** [comment] 2018-01-25 20:20
As a work around, consider registering a singleton `IBusClient`

```csharp
var builder = new ContainerBuilder();
builder
    .Register(c => RawRabbitFactory.CreateSingleton(new RawRabbitOptions()))
    .SingleInstance();
```

Or, if you need an instance per lifetime scope/request/other

```csharp
var builder = new ContainerBuilder();
builder
    .Register(c => RawRabbitFactory.CreateInstanceFactory(new RawRabbitOptions()))
    .SingleInstance();
builder
    .Register(c => c.Resolve<IInstanceFactory>().Create())
    .InstancePerLifetimeScope();
```

**Comment by liri2006** [comment] 2018-02-12 19:24
@pardahlman, actually I'm not using Autofac at all, just the plain MS DI. Those open channel logs appear every 10 seconds and after few hours cause strange bus problems - exceptions about failing to Ack a message or microservice just silently shuts down (I haven't found a reasonable explanation for that because of lack of any king of exception, but most probably it is related to those open channels - system was stable for month without need of a restart before RawRabbit was updated). 
All this is happening on *-rc2 version, after downgrading to *-beta7 those "channel open" logs are gone.

**Comment by pardahlman** [comment] 2018-02-16 18:42
Hi @liri2006 - thanks for reporting this. There are unfortunately a few issues reported that I believe is connected to the `ChannelPool`. Do you know if there is any easy/fast way for me to reproduce what you are experiencing?

**Comment by liri2006** [comment] 2018-02-17 08:26
@pardahlman, I will try to create a sample in a spare time.

**Comment by pardahlman** [comment] 2018-02-17 13:29
@liri2006 re: the acking problem, I've made some changes to how publish acks are performed in #315 - it would be interesting to see if it somehow mitigates the problem you are describing

**Comment by pardahlman** [comment] 2018-02-17 17:07
I tried to reproduce this from the ASP.NET sample in the repo in various ways with no success. Looking forward to a step-by-step on how to reproduce this!

**Comment by pardahlman** [comment] 2018-02-24 09:47
Hi @liri2006 and @afmuller are you still experiencing this? If so, could you give me a step-by-step or perhaps even a minimal sample app that produces this behavior?

**Comment by liri2006** [comment] 2018-02-24 11:19
Hi @pardahlman, here is a quick sample with the problem: https://github.com/liri2006/RawRabbitChannelSample

**Comment by pardahlman** [comment] 2018-02-25 08:14
Hi @liri2006 - here's what I did:

1. Closed you sample
2. Run it using `dotnet run`
3. Wait for for the a couple of _"Channel pool currently has..."_ messages
4. Press `Ctrl+C` to shutdown the application
5. Wait for 30 seconds

After shutting down the application, I don't get any more log entries

![image](https://user-images.githubusercontent.com/1032755/36639384-bb5a948c-1a0b-11e8-8ac9-38c23d9672fa.png)

So, I'm wondering if I have misunderstood you. The screenshot from above are expected log entries and is the result of the `AutoScalingChannelPool` that adds/removes channels if the workload exceeds a configured threshold. There was an issue with the publish acks that was fixed with #315 and is part of rc4 release. Have you tried it out?

**Comment by liri2006** [comment] 2018-02-25 09:48
Hi @pardahlman. So those log entries are not the sign that something is wrong? :) Then I've made false correlations between those logs and bus problems.
I haven't try rc4 yet, downgraded to beta-7 until further investigations.

**Comment by pardahlman** [comment] 2018-02-25 10:32
A-ha! That makes sense.. well, these entries are triggered periodically to check if the workload of the client is above or below certain, configurable, threshold and adds/removes channels from the channel pool accordingly. Mystery solved 😉

**Comment by pardahlman** [comment] 2018-03-11 11:14
Hi, @afmuller - are you still seeing this problem?

**Comment by afmuller** [comment] 2018-03-13 11:44
With my current project I am not using Autofac - and have not noticed this issue. 
Will go back to my Autofac project and re-test.

**Closed as completed** 2019-03-17 14:49 UTC
