### ISSUE TITLE
PipeContextHttpExtensions does not have any methods

### ISSUE THREAD

**Issue by johnnyasantoss** [pardahlman/RawRabbit#208] opened 2017-03-22 21:29 UTC
Hello!
I've just started to use your library and I think I found a bug. I just downloaded `RawRabbit.Enrichers.HttpContext` via Visual Studio 2017 Enterprise, and when I was trying to configure my own Message Context, I din't  found any method in this class.

Is it possible that the last publish `2.0.0-beta-5` have a problem?

Here's some proof:
![Img][photo]

[photo]: http://image.prntscr.com/image/e9893a41ca7d4b779449d330d652af34.png

**Comment by pardahlman** [comment] 2017-03-23 07:33
Hello @johnnyasantoss  👋 - thanks for reporting this!

That looks very strange. What's your target framework? HttpContext is handled differently on the full fx and .net core, so there are a few compiler directives in that class that could be the cause of this.

However, the sample project [uses HttpContext enricher](https://github.com/pardahlman/RawRabbit.Todo/blob/master/src/RawRabbit.Todo.Web/Startup.cs#L40) with the latest version of RawRabbit, and it works fine.

**Comment by pardahlman** [comment] 2017-03-23 10:57
Hello again,
I looked into this some more, and I think I found the issue. I though I removed the file `HttpContextExtensions.cs`, however it looks like I accidentally moved it to under `Properties` which is why I didn't see it

![image](https://cloud.githubusercontent.com/assets/1032755/24244510/8c56f970-0fbf-11e7-878d-c212801eae55.png)

You can read more about how to use the HttpContext enricher [in the jet-net-published documentation](https://github.com/pardahlman/RawRabbit/blob/2.0/docs/enrichers/httpcontext.md)

**Comment by johnnyasantoss** [comment] 2017-03-23 12:10
Hehehehe Ok Thanks for looking into this 😄 
I did found the class under properties, when I was searching for the extension method `GetHttpContext(this IPipeContext context)`, but I forgot to write it in the issue. Sorry ;-;
Answering your question, I'm using the new `.csproj` file structure of .net core targeting `net462`.

Even when I have the `using` of `RawRabbit.Enrichers.HttpContext.Properties` I can't see/use the `GetHttpContext` method.

This is how the lib looks like in Object browser (`Ctrl` + `Alt` + `J`).

![Proof][photo]

[photo]: http://image.prntscr.com/image/2e100bad90ec4370a907fe3ca30bb584.png

**Comment by pardahlman** [comment] 2017-03-24 18:35
Alright @johnnyasantoss turns out that the compiler directives for target framework is case sensitive and I used `#if net451` where it should have been `#if NET451`. I've inspected the binaries after this change and they contain the expected extension methods.

This fix will be included in the next upcoming release.

**Closed by pardahlman** 2017-03-24 18:35 UTC

**Comment by johnnyasantoss** [comment] 2017-03-24 20:03
Thanks!
