### ISSUE TITLE
ApplicationQueueSuffix issue.

### ISSUE THREAD

**Issue by Towmeykaw** [pardahlman/RawRabbit#227] opened 2017-05-22 21:53 UTC
Hello! I had an issue when using the ApplicationQueueSuffix plugin. When i use commandline parameters this tries to match the parameter instead of the name.
``` 
var index = commandLine.Length > 1 ? 1 : 0;
if (DllRegex.IsMatch(commandLine[index]))
```
For now i fixed it by using 
`UseCustomQueueSuffix(PlatformServices.Default.Application.ApplicationName.Replace(".", "_"))`
Which seems to work fine.

**Comment by pardahlman** [comment] 2017-05-23 05:31
Hello, @Towmeykaw - sounds like you've been hit by #193. It is a known issue for all platforms but Windows running on full .NET framework.

I didn't know about `PlatformServices`, looks very interesting. If you want to look into this further, I'm open for a PR that solves #193 on all platforms.

**Comment by garethrampton** [comment] 2017-05-23 08:56
@pardahlman PlatformServices is actually deprecated for Core 2.0, so we're back to Assembly.GetEntryAssembly().GetName().Name to get the current application name again (> .NET Standard 1.5).
See https://github.com/aspnet/PlatformAbstractions/issues/50

**Comment by pardahlman** [comment] 2017-05-23 18:39
Thanks for your input, @garethrampton - there are some interesting discussion in that ticket. @Towmeykaw, I'll close this issue for now, as it is a duplicate of  #193

**Closed by pardahlman** 2017-05-23 18:39 UTC
