### ISSUE TITLE
PublishConfirmException when doing RPC before publishing a message.

### ISSUE THREAD

**Issue by jayrulez** [pardahlman/RawRabbit#274] opened 2017-09-26 04:53 UTC
PublishConfirmException: The broker did not send a publish acknowledgement for message 1 within xx

Error occurs when doing a request immediately before publishing a message.

This test app reproduces the error:

https://github.com/SenitCorp/SenitTest

run the api and browse /api/values

If the order of the statements are changed to put the RPC first then everything works fine.

**Comment by pardahlman** [comment] 2017-09-26 05:29
Hi @jayrulez - thanks for reporting this, I'll try to reproduce it in your sample code and see what can be done about it!

**Comment by jayrulez** [comment] 2017-09-26 16:44
@pardahlman  I seem to have figured out the issue. It's not a problem with RawRabbit per se.

I was returning the wrong type Task.FromResult(0) instead of Task.CompletedTask from my event handler.

I don't know if there was anyway RawRabbit could know what's wrong there.

Any way, we can consider this solved unless you have any input.

Regards.

**Comment by jayrulez** [comment] 2017-09-26 19:22
False positive.

The error is still there.

Not sure why it worked once and just stopped.

I have updated the test app.

Try /test1 /test2 /test3 and /test4 to see the results.

Regards.

**Comment by pardahlman** [comment] 2017-09-29 19:52
Hi again @jayrulez,

I tried reproduce this in the sample app by injecting a publish [right after the RPC request](https://github.com/pardahlman/RawRabbit/blob/2.0/sample/RawRabbit.AspNet.Sample/Controllers/ValuesController.cs#L63)

```csharp
var response = await _busClient.RequestAsync<ValueRequest, ValueResponse>(new ValueRequest {Value = id});
await _busClient.PublishAsync(new TestMessage());
```

...and this worked as expected. I haven't had time to setup your application, but I wonder if it might have something to do with the application setup 🤔 . It would be helpful if you could create a minimal sample where this occurs. You might even be able to change the sample in the RawRabbit solution to get in the faulty state?

**Comment by jayrulez** [comment] 2017-10-02 20:57
Please see https://github.com/pardahlman/RawRabbit/pull/276/commits/8ca32e784f2f4aa6b1c65add797a8d178429a8c6 for reproducing the issue.

Maybe you are not able to reproduce it because you have consumer and producer in a different process.

**Comment by jayrulez** [comment] 2017-10-06 16:35
@pardahlman  any thoughts?

**Comment by pardahlman** [comment] 2017-10-06 19:12
Hello @jayrulez - sorry, not yet. I have had a lot on my plate but will hopefully be able to give this some attention soon

**Comment by pardahlman** [comment] 2017-10-07 09:18
Hello again,

I can reproduce this. It took some time, as I had to figure out what happened in the example code. After a while I could isolate it to an integration test, see below

```csharp
[Fact]
public async Task Throws_Publish_Confirm_Exception_If_Rpc_Response_Sent()
{
  using (var client = RawRabbitFactory.CreateTestClient())
  {
    // Setup 
    await client.RespondAsync<BasicRequest, BasicResponse>(request => Task.FromResult(new BasicResponse()));
    await client.RequestAsync<BasicRequest, BasicResponse>(new BasicRequest());

    try
    {
      // Test
      await client.PublishAsync(new BasicMessage());
    }
    catch (PublishConfirmException e)
    {
      // Assert
      Assert.True(false, e.Message);
    }
    Assert.True(true);
  }
}
```

The problem is not that the request is performed just before the publish, but that the same client publishes the _response_ before the request is published. When debugging the code, I noticed a strange behavior in the underlying `IModel`; it's `NextPublishSeqNo` gets out-of-sync with +1 for each response produced. My theory ATM is that it has to do with execution in multiple threads. Will continue to look into this.

**Comment by pardahlman** [comment] 2017-10-09 16:22
Hello, @jayrulez - this is fixed in rc1 🎉

**Closed by pardahlman** 2017-10-09 16:22 UTC
