### ISSUE TITLE
HandleRetryAsync: Watch out when working with ExchangeBindings

### ISSUE THREAD

**Issue by fgieseke** [pardahlman/RawRabbit#314] opened 2018-02-13 16:06 UTC
The retry queue is configured with
... {QueueArgument.DeadLetterExchange, **deliveryArgs.Exchange**}

Now assume you have an infrastructure as follows:
![image](https://user-images.githubusercontent.com/4338578/36159693-a1b5efde-10df-11e8-88b2-fb4cfe316016.png)

If a message was sent to Exchange A and processing fails in a component subscribing the queue bound to Exchange D then the message gets enqueue in the retry queue but with DeadLetterExchange = Exchange A! (this is where the message came from!)
So after TTL exceeds the message is rerouted to Exchange A and all other exchanges will get this message again! 

The exchangename for the DeadLetterExchange has to be the exchange the subscriber bound it's queue to.

**Comment by pardahlman** [comment] 2018-02-16 12:40
Hi - thanks for reporting this. I'm trying to follow your diagram: are exchange B, C and D bound to exchange A (using [exchange to exchange bindings](https://www.rabbitmq.com/e2e.html))? How did the message end up on Exchange D (is A a topic exchange so that the message is routed to all services?) I think if the message is only delivered to D and you do a retry it is't wrong that it is re-published to A.

**Comment by fgieseke** [comment] 2018-02-16 12:44
Hi
Yes, its an exchange to exchange binding and all exchanges receive the message.

**Comment by pardahlman** [comment] 2018-02-17 07:41
I've been thinking about this scenario and it makes sense. I've updated the middleware so that it tries to use the `ConsumerConfiguration` when deciding which dead letter exchange to use, only using the delivery args as a fallback in the unlikely event that the configuration is not present (this can happen if you create a custom operation based on existing middleware).

Thanks for reporting this!

**Comment by pardahlman** [comment] 2018-02-17 13:07
Closing this for now, as it will be part of the upcoming release. Feel free to reopen this if the problem is still present in `rc4`

**Closed as completed by pardahlman** 2018-02-17 13:07 UTC

**Comment by fgieseke** [comment] 2018-02-19 09:48
Cool. Sounds good. 




Falko 






On Sat, Feb 17, 2018 at 8:41 AM +0100, "Pär Dahlman" <notifications@github.com> wrote:












I've been thinking about this scenario and it makes sense. I've updated the middleware so that it tries to use the ConsumerConfiguration when deciding which dead letter exchange to use, only using the delivery args as a fallback in the unlikely event that the configuration is not present (this can happen if you create a custom operation based on existing middleware).


Thanks for reporting this!
