### ISSUE TITLE
Adding Serilog to dotnet core Console application

### ISSUE THREAD

**Issue by Towmeykaw** [pardahlman/RawRabbit#219] opened 2017-04-21 09:54 UTC
When i try to use DI to add the Serilog logger to my application i run into some issues. 
I have Serilog setup to log to a file but when i do this no RawRabbit logs are written

```csharp
var serviceProvider = new ServiceCollection()
    .AddRawRabbit(new RawRabbitOptions
    {
        DependencyInjection = ioc => ioc
            .AddSingleton<ILoggerFactory, Logging.Serilog.LoggerFactory>()
    })
    .AddSingleton<IMessageSender, Sender>()
.BuildServiceProvider();
```
But if i do this then it works
```csharp
IBusClient _client = RawRabbitFactory.CreateSingleton(new RawRabbitOptions
{			
    DependencyInjection = ioc => ioc.AddSingleton<ILoggerFactory, Logging.Serilog.LoggerFactory>()
});
var serviceProvider = new ServiceCollection()
    .AddSingleton(_client)
    .AddSingleton<IMessageSender, Sender>()
.BuildServiceProvider();
```
Don`t know if i am doing something wrong when setting it up?
And thanks for a great library!

**Comment by pardahlman** [comment] 2017-04-21 10:19
Hej @Towmeykaw 👋 - thanks for reporting this!

It looks like you are running the 2.0 branch - exciting! The code you provided looks great, I think the problem is how RawRabbit resolves it's class specific loggers.

Internal loggers are provided by [`LogManager`](https://github.com/pardahlman/RawRabbit/blob/2.0/src/RawRabbit/Logging/LogManager.cs), typically through a call like this:

```csharp
_logger = LogManager.GetLogger<ChannelFactory>();
``` 

The idea is that during the registration of the bus client, the Log Manager gets assigned it's registered logging factory. Today it done [here](https://github.com/pardahlman/RawRabbit/blob/2.0/src/RawRabbit/Instantiation/RawRabbitFactory.cs#L31). It looks like that code is not being executed when registering the client through the `IServiceCollection` extension method.

This will be addressed in the next pre-release of 2.0. In the mean while, you can either do do what you proposed above, alternatively skip the registration of the logger factory and add register it in the log factory yourself

```csharp
var serilog = new LoggerConfiguration().CreateLogger();
LogManager.CurrentFactory = new RawRabbit.Logging.Serilog.LoggerFactory(serilog);
```

Hope this helps!

**Comment by Towmeykaw** [comment] 2017-04-21 10:45
Okay great! I will keep playing around and look forward to the next release 👍

**Comment by pardahlman** [comment] 2017-05-07 19:16
Heya @Towmeykaw - this issue is fixed in beta6! Happy coding

**Closed by pardahlman** 2017-05-07 19:16 UTC
Labels: 2.0, bug

**Comment by secret-agent-B** [comment] 2019-02-22 15:38
@pardahlman I am doing something similar

```
DependencyInjection = ioc
                        => ioc.AddSingleton<ILoggerFactory, RawRabbit.Logging.Serilog.LoggerFactory>()
```

But the ILoggerFactory that is being implemented by RawRabbit.Logging.Serilog.LoggerFactory is not the same as the one in Microsoft.Extensions.Logging. Which ILoggerFactory should I be using then for this?

![image](https://user-images.githubusercontent.com/15314841/53252953-c084f500-3685-11e9-887a-5a60caf84653.png)

![image](https://user-images.githubusercontent.com/15314841/53252994-d4305b80-3685-11e9-9675-1813f8604003.png)

**Comment by pajej-dev** [comment] 2019-08-07 10:10
Hey @raime910  I have the same problem. We would be greatfull if you could repeat @pardahlman
