### ISSUE TITLE
v2 First subscribed message not raising handler

### ISSUE THREAD

**Issue by stanb** [pardahlman/RawRabbit#228] opened 2017-05-23 12:55 UTC
RawRabbit 2.0.0-betta6
To reproduce run subscriber process that subscribes for several message types.
Then shutdown subscriber.
Publish some messages.
Run subscriber. Messages of the first subscribed message type are not processed. The messages polled from the queue but remains unacked and handler not called.
Messages that published when the subscriber process is running are processed well.
As a workaround I defined dummy message and subscribed to it first.

**Comment by draganjovanovic1** [comment] 2017-05-23 14:19
@stanb, thanks for describing steps for reproduce the issue. I am struggling with the same issue for several days and finally you opened my eyes 👍  

Yes, I can confirm that order of subscription affects weather subscription callback will be called.

**Comment by draganjovanovic1** [comment] 2017-05-23 14:39
Forgot to say, callback is triggered when using NoAck(true)

**Comment by pardahlman** [comment] 2017-05-23 19:48
Hey @stanb - great catch, thanks for reporting this and thanks to you @draganjovanovic1 for providing additional information. 

I have been able to reproduce this myself, and I believe I've found the cause of the problem. You can expect a fix shortly.

**Comment by draganjovanovic1** [comment] 2017-05-23 20:02
@pardahlman, thanks for the feedback.

**Comment by pardahlman** [comment] 2017-05-26 15:06
Fixed in beta7

**Closed by pardahlman** 2017-05-26 15:06 UTC
Labels: 2.0, bug
